alter table TS_EXPENSES add constraint FK_TS_EXPENSES_ACTIVITY_TYPE foreign key (ACTIVITY_TYPE_ID) references TS_ACTIVITY_TYPE(ID);
create index IDX_TS_EXPENSES_ACTIVITY_TYPE on TS_EXPENSES (ACTIVITY_TYPE_ID);
